### ISSUE TITLE
Suggestions for improving EU-VIES support

### ISSUE THREAD

**Issue by vdboor** [ralphje/django-internationalflavor#1]
To improve the VAT number field, I'd suggest:

- Allow any country type by default.
- only perform a VIES check on EU member states. (now it implies eu_only=True)
- apply regex checks on other countries, whatever is possible.

I'd prefer having one VAT field, which supports any international number.

**Comment by ralphje** [comment]
Hi @vdboor, thank you for your suggestions!

All countries for which a VAT number regex is available, are accepted by default. I don't feel that accepting just anything for unknown countries is a good solution. If you want to suggest new regexes, feel free to add them to this issue or submit a pull request.

I have modified the code to not imply `eu_only` anymore when `vies_check` is set. If the latter is `True`, only VAT numbers from the EU VAT area are validated against VIES, other VAT numbers remain unaffected.

However, please note that the reason for implying `eu_only` was a regulatory one: if you must validate against VIES, you must also use `eu_only`. I have included a note for this in the documentation.

These fixes will be included in a future release.

**Comment by vdboor** [comment]
thanks! :-)

> I have modified the code to not imply eu_only anymore when vies_check is set. If the latter is True, only VAT numbers from the EU VAT area are validated against VIES, other VAT numbers remain unaffected.

Wonderful, thanks!

> However, please note that the reason for implying eu_only was a regulatory one: if you must validate against VIES, you must also use eu_only. I have included a note for this in the documentation.

I can understand where you are coming from, and that makes perfect sense. My point of reference is an international shop, where people can enter their VAT number. In that case, having a VIES-check is a nice extra benefit, but no matter what, we want people to be able to enter their VAT number even if we don't have a regex for their country yet.
