### ISSUE TITLE
Not sorted countries

### ISSUE THREAD

**Issue by eriktelepovsky** [ralphje/django-internationalflavor#13]
Hi. The choices of CountryFormField are not sorted. Is it a purpose?

Right now, I have to use choices argument to fix that like this:

```
choices = sorted(get_countries_lazy(), key=lambda o: o[1])
```

It would be great if the choices are sorted by country name by default.

**Comment by ralphje** [comment]
The should be, through the SortedSelect widget. It lazily sorts, so it works properly with different translations. Is your form using that widget?

**Comment by eriktelepovsky** [comment]
Yes, I already tried to use:

```
widget=SortedSelect()
```

and it worked for a while. Then I updated to Django 1.11.7 and it stopped working. Also, default model fields in the admin do not have sorted country choices:

![image](https://user-images.githubusercontent.com/2685808/34007529-668b9f24-e102-11e7-97fc-3ca918e7909e.png)

**Comment by ralphje** [comment]
That's a shame. I'll look into it.

**Comment by ralphje** [comment]
I checked and it should work since commit:9677b8053b090ab5eb91fce31e9eaa8ba880c815. That commit hasn't made it into a release yet. Could you verify the current master fixes the issue?

**Comment by eriktelepovsky** [comment]
Yes, I confirm. Works fine in the current master ;) Thank you.

**Comment by eriktelepovsky** [comment]
I would like to reopen this issue:

```
country = forms.ChoiceField(label=_('Country'), choices=[('', _('Choose a country'))] + list(get_countries_lazy()))
```

it is sorted by keys, not values:

![image](https://user-images.githubusercontent.com/2685808/120480193-12fa0380-c3af-11eb-8e41-43ec9bf15038.png)
