### ISSUE TITLE
GB country code still in EU_VAT_AREA

### ISSUE THREAD

**Issue by Rocky-travelperk** [ralphje/django-internationalflavor#20]
Hi, checking the code I see that the United Kingdom code "GB" still part of the  `EU_VAT_AREA`. Are there any reason why is there after Brexit? 
https://github.com/ralphje/django-internationalflavor/blob/c9c7f65eeea7048cd6360377ec70b98d61b26d13/internationalflavor/vat_number/data.py#L86
Thanks

**Comment by ivankzl** [comment]
Any news on this issue?

**Comment by ralphje** [comment]
I will investigate in the near future
