### ISSUE TITLE
IBAN comparison with other apps is not correct

### ISSUE THREAD

**Issue by benkonrath** [ralphje/django-internationalflavor#3]
Hi, Great work on this module. I'm probably going to use the VAT field in my project.

I'm the author of django-iban which was the basis for the django-localflavor IBAN and BIC fields. Your comparison documentation is not correct and it would be nice to have this corrected.
```
This module also supports a IBANField, but does not validate against regular expressions, rather validating the length of the IBAN for each country code. The validation provided by :mod:`internationalflavor` is more extensive by using regular expressions.
```
The IBAN fields in django-localflavor does in fact check the length for the specific country but it also does a full checksum validation as per the official IBAN validation guide (just like your code).

https://github.com/django/django-localflavor/blob/1.1/localflavor/generic/validators.py#L111

As far as I can see, there is no real functional difference between your version and the version in django-localflavor. But I would love to work together on making the django-localflavor version better if there is a problem with it. The reason I contributed the code to django-localflavor was so that there could be a community maintained version of this validation rather than a bunch of solo devs trying to hack this out on our own.

```
Additionally, we provide a :class:`BICField` for SWIFT BIC validation.
```
This is also not correct. django-localflavor has a BICField as well.

https://github.com/django/django-localflavor/blob/1.1/localflavor/generic/models.py#L55

Like I said, if there is a problem with the localflavor versions of the IBAN or BIC fields, I would be very happy to see a bug report or review a PR against django-localflavor. At the very least, your documentation should be updated to accurately reflect the differences between the two versions (which seems to be nothing).

**Comment by ralphje** [comment]
I agree that the comparison in the documentation may be a bit shortsighted.

The main difference between both versions is that your version (in addition to validating the checksum) only validates the length of the IBAN, not which characters are actually allowed in the country-specific IBAN. See https://github.com/ralphje/django-internationalflavor/blob/master/internationalflavor/iban/data.py#L7-L76 for the regexes I use. For instance, you would validate NLXX12340123456789 as being valid (with XX replaced with the correct checksum), although Dutch IBANs actually are formatted like NLXXINGB0123456789. 

The formats for each of these are listed in http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf. (I see that my data.py is a bit outdated anyway, so I'll try to dedicate some time to updating and finalizing this package again in the near future.)

I may have totally missed the BICField and agree this is incorrectly listed as missing feature in the comparison.

By the way, the main reason I created internationalflavor is that I wanted to eliminate country-specific fields to some extent, and make fields that apply to most international companies. IMO, IBAN is too international to be localflavor :smile: .

**Comment by benkonrath** [comment]
No problem, I was just surprised to see issues with localflavor IBAN in your docs without hearing about them in a bug report or PR. I also think having competing validation fields like this adds confusion to the Django ecosystem and misses a big benefit of open source which is a shared solution for common problems.

Thanks for pointing out the regex data, I see your point now about allowing syntactically invalid IBANs. But in practice this is not an issue because the checksum would catch issues unless people purposely generate IBANs to fool the validation. That said, I'm definitely open to adding the regex validation to django-localflavor. Would you be interested in making a pull request against localflavor to add support for the regex validation?

There's a generic module in localflavor precisely for fields that are cross-country or international in nature. Of course that doesn't preclude you from continuing this module, I just wanted to point it out so that you can mention in your docs for completeness.

**Comment by ralphje** [comment]
I'll try to find the time to issue a PR for the localflavor version. In the meantime, I have updated the documentation of internationalflavor with more accurate information regarding your version.

**Comment by benkonrath** [comment]
Thanks! I'm looking forward to seeing the PR if / when you have time.

**Comment by benkonrath** [comment]
Just a quick follow up. I'm going add the proper format validation to the localflavor IBAN fields using [python-stdnum](http://arthurdejong.org/python-stdnum/). I wanted to let you know so that you don't spend time on this. Thanks.
