### ISSUE TITLE
Ireland VAT numbers issued after 2013 not accepted

### ISSUE THREAD

**Issue by cbay** [ralphje/django-internationalflavor#8]
The current regexp seems to match the old format, the new format is not accepted.

More details:
https://www.meridianglobalservices.com/blog/2013/01/01/New-tax-number-format-Ireland

Example of VAT number not accepted:
1234567FA

**Comment by israel-tk** [comment]
Hey, can you please make a pypi release with this fix?

**Comment by ralphje** [comment]
Done.
